version: "3.4"

services:
    sut:
        image: >-
          ${IMAGE_NAME}:${IMAGE_BUILD_ID}
        environment:
          CERTHUB_MESSAGE_SUBJECT_ACTION: >-
            Issue/renew by Travis CI Run [#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})
          CERTHUB_CERT_PATH: >-
            {WORKDIR}/${IMAGE_VARIANT}-docker-test.fullchain.pem
          CERTHUB_CSR_PATH: >-
            ${IMAGE_VARIANT}-docker-test.csr.pem
          GAU_REPO: >-
            git@github.com:certhub/certhub-scratch-certs.git
          GAU_SSH_PRIVKEY: >-
            ${PRIVATE_SSH_KEY}
          GAU_SSH_KNOWNHOSTS: |
            github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          GIT_AUTHOR_NAME: >-
            Certhub CI
          GIT_AUTHOR_EMAIL: >-
            travis-ci@certhub.io
          GIT_COMMITTER_NAME: >-
            Certhub CI
          GIT_COMMITTER_EMAIL: >-
            travis-ci@certhub.io

    config:
        environment:
          CONFIG_CSR_PATH: >-
            ${IMAGE_VARIANT}-docker-test.csr.pem
          CONFIG_CERT_CN: >-
            ${IMAGE_VARIANT}-docker-test--travis-build-${TRAVIS_BUILD_ID}.ci.certhub.io
