version: "3.4"

services:
    sut:
        image: >-
          ${IMAGE_NAME}:${IMAGE_BUILD_ID}
        environment:
          CERTHUB_MESSAGE_SUBJECT_ACTION: >-
            Issue/renew by Travis CI Run [#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})
          CERTHUB_CERT_PATH: >-
            {WORKDIR}/${IMAGE_VARIANT}-docker-test.fullchain.pem
          CERTHUB_CSR_PATH: >-
            ${IMAGE_VARIANT}-docker-test.csr.pem
          GAU_REPO: >-
            git@github.com:certhub/certhub-scratch-certs.git
          GAU_SSH_PRIVKEY: >-
            ${PRIVATE_SSH_KEY}
          GAU_SSH_KNOWNHOSTS: |
            github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          GIT_AUTHOR_NAME: >-
            Certhub CI
          GIT_AUTHOR_EMAIL: >-
            travis-ci@certhub.io
          GIT_COMMITTER_NAME: >-
            Certhub CI
          GIT_COMMITTER_EMAIL: >-
            travis-ci@certhub.io

    config:
        environment:
          CONFIG_CSR_PATH: >-
            ${IMAGE_VARIANT}-docker-test.csr.pem
          CONFIG_CERT_CN: >-
            ${IMAGE_VARIANT}-docker-test--travis-build-${TRAVIS_BUILD_ID}.ci.certhub.io
