version: "3.4"

services:
    sut:
        image: >-
          ${IMAGE_NAME}:${IMAGE_BUILD_ID}
        environment:
          CERTHUB_MESSAGE_SUBJECT_ACTION: >-
            Issue/renew by GH Build [#${GITHUB_RUN_NUMBER}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})
          CERTHUB_CERT_PATH: >-
            {WORKDIR}/${IMAGE_VARIANT}-docker-test.fullchain.pem
          CERTHUB_CSR_PATH: >-
            ${IMAGE_VARIANT}-docker-test.csr.pem
          GAU_REPO: >-
            git@github.com:certhub/certhub-scratch-certs.git
          GAU_SSH_PRIVKEY: >-
            ${PRIVATE_SSH_KEY}
          GAU_SSH_KNOWNHOSTS: |
            github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          GIT_AUTHOR_NAME: >-
            ${GITHUB_ACTOR}
          GIT_AUTHOR_EMAIL: >-
            ${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com
          GIT_COMMITTER_NAME: >-
            ${GITHUB_ACTOR}
          GIT_COMMITTER_EMAIL: >-
            ${GITHUB_ACTOR}@users.noreply.github.com

    config:
        environment:
          CONFIG_CSR_PATH: >-
            ${IMAGE_VARIANT}-docker-test.csr.pem
          CONFIG_CERT_CN: >-
            ${IMAGE_VARIANT}-docker-test--gh-build-${GITHUB_RUN_ID}.ci.certhub.io
